"""Initial migration

Revision ID: c9f28906849c
Revises: 
Create Date: 2024-07-02 23:03:08.441295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9f28906849c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True, comment='Name of the company associated with the user'),
    sa.Column('first_name', sa.String(), nullable=True, comment='First name of the user'),
    sa.Column('last_name', sa.String(), nullable=True, comment='Last name of the user'),
    sa.Column('email', sa.String(), nullable=True, comment='Email address of the user'),
    sa.Column('password', sa.String(), nullable=True, comment='Password of the user'),
    sa.Column('mobile', sa.String(), nullable=True, comment='Mobile number of the user'),
    sa.Column('hashtag', sa.String(), nullable=True, comment='Hashtag associated with the user'),
    sa.Column('date_of_birth', sa.Date(), nullable=True, comment='Date of birth of the user'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Timestamp of when the user was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Timestamp of when the user was last updated'),
    sa.Column('is_active', sa.Integer(), nullable=True, comment='Flag to indicate if the user is active or not'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=False)
    op.create_index(op.f('ix_User_first_name'), 'User', ['first_name'], unique=False)
    op.create_index(op.f('ix_User_id'), 'User', ['id'], unique=False)
    op.create_index(op.f('ix_User_last_name'), 'User', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_last_name'), table_name='User')
    op.drop_index(op.f('ix_User_id'), table_name='User')
    op.drop_index(op.f('ix_User_first_name'), table_name='User')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###
